<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WINDOWS-R8SKFHD" failures="2" tests="2" name="Validating User login" time="347.786" errors="0" timestamp="25 Mar 2022 13:28:36 GMT">
  <testcase classname="cucmberOptions.TestRunner" name="feature" time="346.149">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: expected [Account already exists with this mobile number. Please login.] but found [Invalid mobile number.]
	at stepDefinations.stepDefination.verify_that_user_is_successfully_logged_in(stepDefination.java:105)
	at âœ½.Then Verify that user is successfully logged in(src/test/java/features/Login.feature:8)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
  <testcase classname="cucmberOptions.TestRunner" name="feature" time="346.329">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)&amp;quot; because &amp;quot;ts&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)" because "ts" is null
	at resources.base.getScreenShotPath(base.java:67)
	at Shopclues.Listeners.onTestFailure(Listeners.java:47)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Validating User login -->
